### ISSUE TITLE
err if no environment.py

### ISSUE THREAD

**Issue by zenyusy** [avanzzzi/behave.vim#9]
https://github.com/avanzzzi/behave.vim/blob/fc698f1264710beb7070d9282874ddfc83e64db5/autoload/behave.py#L11

hi, i tried using this plugin in a behave dir which is so minimal that there is no "environment.py" (like the one in test/ , or the official tutorial's first demo), then this `exec_file` will raise error.

maybe change to `if file exist: exec_file(file)` ?

**Comment by ea2809** [comment]
Great question, I would love to help you, but I do not remember why I did that change...  As far as I can remember, this code was a copy from behave internal logic. 

Would you mind to make a PR with the changes after you check it locally? 🙇‍♂️
